### PR TITLE
Drop 'the' in title and drop Princeton logo.

### PR DESCRIPTION
**Pull request by jpivarski**
"The modern" sounded too strong (doesn't admit of alternatives).

Also, for the three of us, the Princeton logo is not appropriate. I adjusted the position of the IRIS-HEP logo.

### CODE REVIEW

**Comment by jpivarski** [comment]
And PDFs are generated now.

**Comment by matthewfeickert** [comment]
> "The modern" sounded too strong (doesn't admit of alternatives).

That's what the title was in the copy that we sent out that you and Gordon approved. Modern also doesn't mean that it is the _only_ way to do something. Though we can drop it if you don't like it.
 
> Also, for the three of us, the Princeton logo is not appropriate. I adjusted the position of the IRIS-HEP logo.

I was assuming that we would just add the Wisconsin and Washington logos, but I didn't take time to do that last night.

**Comment by matthewfeickert** [comment]
> And PDFs are generated now.

I added the PDFs even though they can be generated from the SVG to make the CI work easier. We can also just install `imagemagick` to do the conversion, but adding a few PDF files seemed easier.

**Comment by jpivarski** [comment]
I usually check both SVG and PDF into the repo, and don't even include `inkscape` in the build process. Whichever is fine with me—the build is failing because CI doesn't have Inkscape installed; it seems like too much trouble for some slides that need to be done by Wednesday.

**Comment by matthewfeickert** [comment]
> I usually check both SVG and PDF into the repo, and don't even include `inkscape` in the build process

Cool let's just do that for now.

I restored the PDF and SVG files that were removed as it would be nice to have them on the title screen if there is time. I think we can worry about that later, but there is a branch `fix/get-all-logos-on-title` that if you get bored on Wednesday morning and want to fix things we can do from a PR from there.

**Pull request merged**
